name       : qt6-multimedia
version    : 6.3.0
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtmultimedia-everywhere-src-6.3.0.tar.xz : d050247ff82974a8480c05ce602fd39e03d9e2d1b82bb78a3f42cf29b3a7fe3e
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Multimedia Components
description: |
    Qt Multimedia is an essential module that provides a rich set of QML types and C++ classes to handle multimedia content. It also provides necessary APIs to access the camera and radio functionality. The included Qt Audio Engine provides types for 3D positional audio playback and content management.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(gstreamer-plugins-bad-1.0)
rundeps    :
    - devel :
        - gstreamer-1.0-plugins-bad-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
